# Generated by Django 2.2.16 on 2022-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220504_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_index=True, to='reviews.Genre', verbose_name='Жанры'),
        ),
    ]
